/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inventory.UI;

import com.inventory.DAO.BillsDAO;
import com.inventory.DAO.CustomerDAO;
import com.inventory.DAO.ProductDAO;
import com.inventory.DTO.ProductDTO;
import com.inventory.DTO.BillsDTO;
import com.inventory.Util.PdfExporter;
import com.inventory.Util.PrintHelper;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.List;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author asjad
 */
public class SalesPage extends javax.swing.JPanel {

    String username;
    Dashboard dashboard;
    int quantity;
    String prodCode;

    // === NEW: dynamic product rows support ===
    private JPanel itemsPanel;               // holds ProductRow panels (vertical list)
    private JScrollPane itemsScrollPane;     // scroll for itemsPanel
    private JButton addItemButton;           // "+ Add Product" button
    private final java.util.List<ProductRow> productRows = new ArrayList<>();

    /**
     * Creates new form SalesPage
     */

    public SalesPage(String username, Dashboard dashboard) {
        initComponents();
        this.username = username;
        this.dashboard = dashboard;
        custNameLabel.setVisible(false);
        // prodNameLabel removed — per-row product info labels are used
        loadDataSet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        refreshButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sellPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        custCodeText = new javax.swing.JTextField();
        custIdText = new javax.swing.JTextField();
//        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        sellButton = new javax.swing.JButton();
        downloadButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        addCustButton = new javax.swing.JButton();
        custNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        searchText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        // === NEW UI bits for multi-products ===
        JLabel productsHeaderLabel = new JLabel("Products (Name, Price, Quantity):");
        itemsPanel = new JPanel();
        itemsPanel.setLayout(new BoxLayout(itemsPanel, BoxLayout.Y_AXIS));
        itemsScrollPane = new JScrollPane(itemsPanel);
        addItemButton = new JButton("+ Add Product");

        // Add first empty product row
        addProductRow();

        addItemButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addItemButton.addActionListener(e -> addProductRow());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setText("SALES");

        sellPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sell Product"));

        jLabel2.setText("Customer Name:");

//        jLabel4.setText("Date:");

        custCodeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                custCodeTextKeyReleased(evt);
            }
        });

        sellButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sellButton.setText("SELL PRODUCT");
        sellButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        downloadButton.setFont(new java.awt.Font("Segoe UI", 1, 12));
        downloadButton.setText("Save as Pdf");
        downloadButton.setForeground(Color.RED);
        downloadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });

        printButton.setFont(new java.awt.Font("Segoe UI", 1, 12));
        printButton.setText("Print");
        printButton.setForeground(Color.RED);
        printButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        addCustButton.setText("Click to add a New Customer");
        addCustButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustButtonActionPerformed(evt);
            }
        });
        refreshButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        custNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custNameLabel.setLabelFor(custCodeText);

        // ----- sellPanel layout (GroupLayout), keeping original style, just inserting new components -----
        javax.swing.GroupLayout sellPanelLayout = new javax.swing.GroupLayout(sellPanel);
        sellPanel.setLayout(sellPanelLayout);

        sellPanelLayout.setHorizontalGroup(
                sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sellPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(sellPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(custCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(custNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addCustButton)
                                        .addGroup(sellPanelLayout.createSequentialGroup()
//                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                )
                                        .addComponent(productsHeaderLabel)
                                        .addComponent(itemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addItemButton)
                                        .addGroup(sellPanelLayout.createSequentialGroup()
                                                .addComponent(deleteButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(clearButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(sellButton)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        sellPanelLayout.setVerticalGroup(
                sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sellPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(custCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addCustButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        )
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(productsHeaderLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addItemButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deleteButton)
                                        .addComponent(clearButton)
                                        .addComponent(sellButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        salesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salesTable);

        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextKeyReleased(evt);
            }
        });

        jLabel7.setText("Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(downloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(refreshButton))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(sellPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(downloadButton)
                                        .addComponent(printButton)
                                        .addComponent(jLabel7)
                                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                )
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sellPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt){
        String tableHeading = "Sales Report";
        PdfExporter.exportToPDF(salesTable, tableHeading);
    }

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt){
        String printHeading = "Sales Report";
        PrintHelper.print(salesTable, printHeading);
    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (salesTable.getSelectedRow()<0)
            JOptionPane.showMessageDialog(this, "Please select an entry from the table you wish to delete.");
        else {
            int opt = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete this sale from the database?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION);
            if (opt == JOptionPane.YES_OPTION) {
                new ProductDAO().deleteSaleDAO(Integer.parseInt(
                        salesTable.getValueAt(salesTable.getSelectedRow(),0).toString()));
                new ProductDAO().editSoldStock(
                        salesTable.getValueAt(salesTable.getSelectedRow(),1).toString(), quantity);
                loadDataSet();
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        custCodeText.setText("");
        custNameLabel.setText("");
        custNameLabel.setVisible(false);
//        jDateChooser1.setDate(null);

        // clear all product rows and add a fresh empty one
        itemsPanel.removeAll();
        productRows.clear();
        addProductRow();

        itemsPanel.revalidate();
        itemsPanel.repaint();

        loadDataSet();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void addCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustButtonActionPerformed
        dashboard.addCustPage();
    }//GEN-LAST:event_addCustButtonActionPerformed

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        String customerCode = "";
        if (custCodeText.getText().trim().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Please fill Customer Name.");
            return;
        }

        // validate customer first
        try {
            ResultSet resultSet = new CustomerDAO().getCustById(custIdText.getText().trim());
            if (!resultSet.next()) {
                JOptionPane.showMessageDialog(this, "This customer does not exist.\n" +
                        "Add new customer or use a valid customer code.");
                return;
            }
            customerCode = resultSet.getString("customercode");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error while verifying customer.");
            return;
        }

        if (productRows.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please add at least one product row.");
            return;
        }

        // iterate rows and sell each valid product
        int soldCount = 0;

            // Build DTO and call DAO like original logic
            try {
                // get system date with required format (ex : Thu Oct 02 23:31:45 IST 2025)
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEE MMM dd HH:mm:ss z yyyy");
                ZonedDateTime now = ZonedDateTime.now(ZoneId.of("Asia/Kolkata"));
                String formattedDate = now.format(formatter);

                ProductDTO productDTO = new ProductDTO();
                CustomerDAO customerDAO = new CustomerDAO();
                ProductDAO productDAO = new ProductDAO();
                productDTO.setCustCode(customerCode);
                productDTO.setDate(formattedDate);
                int totalRevenue = 0;

                boolean flag = false;
                for(BillsDTO item: billItems){
                    totalRevenue += item.getUnitPrice() * item.getQuantity();
                    productDTO.setProdCode(item.getProductCode());
                    productDTO.setQuantity(item.getQuantity());
                    productDTO.setTotalRevenue(totalRevenue);
                    flag = productDAO.sellProductAndMaintainStock(item.getProductId(), item.getQuantity());
                    if(!flag){
                        JOptionPane.showMessageDialog(null, "Stock not available for item(s) in this sale please verify and Try Again");
                        return;
                    }
                    productDAO.sellProductDAO(productDTO, username);
                }

                BillsDAO billsDAO = new BillsDAO();
                String billId = billsDAO.createNewBill(custIdText.getText().trim(), totalRevenue);
                for(BillsDTO item : billItems){
                    billsDAO.addBillItems(billId, item);
                    soldCount++;
                }

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Failed to sell a product");
                return;
            }

        if (soldCount == 0) {
            JOptionPane.showMessageDialog(this, "No valid product rows to sell.");
            return;
        }

        loadDataSet();
        JOptionPane.showMessageDialog(this, "Sold " + soldCount + " item(s).");
    }//GEN-LAST:event_sellButtonActionPerformed

    private void salesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesTableMouseClicked
        int row = salesTable.getSelectedRow();
        int col = salesTable.getColumnCount();
        Object[] data = new Object[col];
        for (int i=0; i<col; i++)
            data[i] = salesTable.getValueAt(row, i);
        quantity = Integer.parseInt(data[3].toString());
        prodCode = data[1].toString();
    }//GEN-LAST:event_salesTableMouseClicked

    private void custCodeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custCodeTextKeyReleased
        try {
            ResultSet resultSet = new CustomerDAO().getCustIdFromName(custCodeText.getText().trim());
            if (resultSet.next()) {
                custNameLabel.setText("Full Name: " + resultSet.getString("fullname") + " | Customer Id: "
                        + resultSet.getString("cid")
                );
                custIdText.setText(resultSet.getString("cid"));
            }
            else
                custNameLabel.setText("||   Customer doesn't exist in database.   ||");
            custNameLabel.setVisible(true);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_custCodeTextKeyReleased

    private void searchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyReleased
        loadSearchData(searchText.getText());
    }//GEN-LAST:event_searchTextKeyReleased

    // Method to load data into table
    public void loadDataSet() {
        try {
            ProductDAO productDAO = new ProductDAO();
            DefaultTableModel model = productDAO.buildTableModel(productDAO.getSalesInfo());
            salesTable.setModel(model);

            //sorting in table
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
            // Set numeric comparators for the appropriate columns
            sorter.setComparator(3, Comparator.comparingInt(o -> Integer.parseInt(o.toString()))); // Quantity
            sorter.setComparator(4, Comparator.comparingInt(o -> Integer.parseInt(o.toString()))); // Revenue
            sorter.setComparator(5, (o1, o2) -> { //datetime
                SimpleDateFormat format = new SimpleDateFormat("E MMM dd HH:mm:ss z yyyy", Locale.ENGLISH);
                try {
                    Date d1 = format.parse(o1.toString());
                    Date d2 = format.parse(o2.toString());
                    return d1.compareTo(d2);
                } catch (ParseException e) {
                    return 0; // treat as equal if parsing fails
                }
            });
            salesTable.setRowSorter(sorter);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Method to display search result in table
    public void loadSearchData(String text) {
        try {
            ProductDAO productDAO = new ProductDAO();
            DefaultTableModel model = productDAO.buildTableModel(productDAO.getSalesSearch(text));
            salesTable.setModel(model);

            //sorting in table
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
            // Set numeric comparators for the appropriate columns
            sorter.setComparator(3, Comparator.comparingInt(o -> Integer.parseInt(o.toString()))); // Quantity
            sorter.setComparator(4, Comparator.comparingInt(o -> Integer.parseInt(o.toString()))); // Revenue
            sorter.setComparator(5, (o1, o2) -> { //datetime
                SimpleDateFormat format = new SimpleDateFormat("E MMM dd HH:mm:ss z yyyy", Locale.ENGLISH);
                try {
                    Date d1 = format.parse(o1.toString());
                    Date d2 = format.parse(o2.toString());
                    return d1.compareTo(d2);
                } catch (ParseException e) {
                    return 0; // treat as equal if parsing fails
                }
            });
            salesTable.setRowSorter(sorter);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // === Helper: add a new product row ===
    private void addProductRow() {
        ProductRow row = new ProductRow();
        productRows.add(row);
        itemsPanel.add(row);
        itemsPanel.revalidate();
        itemsPanel.repaint();
    }

    // === Per-row UI for (Product Code, Quantity) ===
    private class ProductRow extends JPanel {
        JTextField prodNameField = new JTextField(0);
        JTextField priceField = new JTextField(0);
        JTextField quantityField = new JTextField(0);
        JLabel infoLabel = new JLabel(" ");
        String prodId = "";


        ProductRow() {
            setLayout(new GridBagLayout());
            GridBagConstraints gc = new GridBagConstraints();
            gc.insets = new Insets(1, 1, 1, 1);
            gc.gridy = 0;

            // Product Code
            gc.gridx = 0;
            add(new JLabel("Name:"), gc);
            gc.gridx = 1;
            add(prodNameField, gc);

            // Price
            gc.gridx = 2;
            add(new JLabel("Price:"), gc);
            gc.gridx = 3;
            add(priceField, gc);

            // Quantity
            gc.gridx = 4;
            add(new JLabel("Qty:"), gc);
            gc.gridx = 5;
            add(quantityField, gc);

            // Info label (spans full width next row)
            gc.gridx = 0; gc.gridy = 1; gc.gridwidth = 3;
            infoLabel.setFont(infoLabel.getFont().deriveFont(Font.PLAIN, 11f));
            add(infoLabel, gc);

            // Auto-fill product name/available qty and price on code typing
            prodNameField.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    String code = prodNameField.getText().trim();
                    if (code.isEmpty()) {
                        infoLabel.setText(" ");
                        priceField.setText("");
                        return;
                    }
                    try {
                        ResultSet rs = new CustomerDAO().getProdName(code);
                        if (rs.next()) {
                            String nm = rs.getString("productname");
                            String avail = rs.getString("quantity");
                            prodId = rs.getString("pid");
                            infoLabel.setText("Name: " + nm + " | Available: " + avail);
                            Integer sellPrice = new ProductDAO().getProdSell(rs.getString("productcode"));
                            priceField.setText(sellPrice != null ? sellPrice.toString() : "");
                            priceField.setEditable(true);
                        } else {
                            infoLabel.setText("||   Product doesn't exist in Inventory.  ||");
                            priceField.setText("");
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                        infoLabel.setText("Error fetching product info.");
                    }
                }
            });

            quantityField.addFocusListener(new java.awt.event.FocusAdapter(){
                @Override
                public void focusLost(java.awt.event.FocusEvent evt) {
                    String pCode = prodNameField.getText().trim();
                    int price = Integer.parseInt(priceField.getText().trim());
                    int qty = Integer.parseInt(quantityField.getText().trim());
                    String custId = custIdText.getText().trim();

                    BillsDTO item = new BillsDTO(prodId, custId, qty, price, pCode);
                    billItems.add(item);
                    System.out.println(Arrays.toString(billItems.toArray()));
                }
            });
            quantityField.addActionListener(e -> addProductRow());

        }
    }
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        loadDataSet();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField custCodeText;
    private javax.swing.JTextField custIdText;
    private javax.swing.JLabel custNameLabel;
    private javax.swing.JButton deleteButton;
//    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable salesTable;
    private javax.swing.JTextField searchText;
    private javax.swing.JButton downloadButton;
    private javax.swing.JButton printButton;
    private javax.swing.JButton sellButton;
    private javax.swing.JPanel sellPanel;
    private List<BillsDTO> billItems = new ArrayList<>();
    private javax.swing.JButton refreshButton;

    // End of variables declaration//GEN-END:variables
}
